### ISSUE TITLE
Update the wireframe to include placeholders for each core feature

### ISSUE THREAD

**Issue by kdkleven** [kdkleven/uofm-bootcamp-project1#1]
Core features:
- Input field for zip code/city
- list of activities
- submit button
- weather section, with a card displaying today's weather: current temp, high temp, low temp, windspeed, and humidity (in farenheit)
- activities section, with cards for each activity, containing: activity category, title, description, location/address, and thumbnail/image

**Comment by ghost** [comment]
Updated wireframe with basic design for core features. Added id's to allow for targeting with Javascript.
